version: "3.8"

services:
  app:
    image: 2048-game
    build:
      context: .
      dockerfile: Dockerfile d
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  app2:
    image: 2048-game-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
networks:
  default:
    driver: bridge
